#!/usr/bin/env bash
# scripts/build-registry.sh
# Aggregates per-task manifest.yaml files into tasklab/registry.yaml.
# Usage: ./scripts/build-registry.sh [--tasks-dir <path>] [--output <path>]
set -euo pipefail

TASKS_DIR="${TASKS_DIR:-tasklab/tasks}"
OUTPUT="${OUTPUT:-tasklab/registry.yaml}"

while [[ $# -gt 0 ]]; do
  case $1 in
    --tasks-dir) TASKS_DIR="$2"; shift 2 ;;
    --output)    OUTPUT="$2";    shift 2 ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
done

require_command() { command -v "$1" &>/dev/null || { echo "Required: $1" >&2; exit 1; }; }
require_command yq

{
  echo "# tasklab/registry.yaml"
  echo "# Generated by scripts/build-registry.sh — do not edit by hand"
  echo "generated: $(date +%Y-%m-%d)"
  echo ""
  echo "tasks:"
} > "$OUTPUT"

find "$TASKS_DIR" -name "node_modules" -prune -o -name "task.yaml" -print | sort | while read -r task_yaml; do
  task_dir="$(dirname "$task_yaml")"
  manifest="$task_dir/manifest.yaml"

  rel="${task_dir#"$TASKS_DIR/"}"
  service="${rel%%/*}"
  task_slug="${rel#"$service/"}"

  if [[ -f "$manifest" ]]; then
    maturity="$(yq '.maturity // 0' "$manifest")"
    run_count="$(yq '.runs | length' "$manifest")"
    promo="$(yq '.promotion_notes // ""' "$manifest")"
    if [[ "$run_count" -gt 0 ]]; then
      last_run="$(yq '.runs[-1].date // "null"'        "$manifest")"
      last_outcome="$(yq '.runs[-1].outcome // "null"' "$manifest")"
    else
      last_run="null"; last_outcome="null"
    fi
  else
    maturity=0; last_run="null"; last_outcome="null"; run_count=0; promo=""
  fi

  cat >> "$OUTPUT" <<ENTRY
  - service: $service
    task: $task_slug
    maturity: $maturity
    last_run: $last_run
    last_outcome: $last_outcome
    run_count: $run_count
    promotion_notes: "$promo"
    path: $task_dir
ENTRY
done

echo "Registry written to $OUTPUT"
